OPENAI_API_KEY = "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"
email_sender = "akp714200@gmail.com"
email_password = "xfzgbdbzghwaanjm"